[versions]
appcompat = "1.7.0"
transition = "1.5.1"
fragment = "1.8.6"
viewpager2 = "1.1.0"
swiperefresh = "1.1.0"
recyclerview = "1.3.1"
drawerlayout = "1.2.0"
cardview = "1.0.0"
coordinatorlayout = "1.1.0"
constraintlayout = "2.0.1"
flexbox = "3.0.0"
glide = "4.16.0"
webviewup = "0.1.0"
activity = "1.9.3"
fastscroll = "1.2.0"
agp = "8.6.0"
core = "1.16.0"
splashscreen = "1.2.0-rc01"

[libraries]
# AndroidX
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat" }
androidx-transition = { group = "androidx.transition", name = "transition", version.ref = "transition" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-swiperefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core"}
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }

# Google
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }

# Third-party
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
webviewup-core = { group = "io.github.jonanorman.android.webviewup", name = "core", version.ref = "webviewup" }
fastscroll = { group = "me.zhanghai.android.fastscroll", name = "library", version.ref = "fastscroll" }

# Activity
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }